import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PhaseButtons from "@/components/PhaseButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen flex-col items-center justify-start p-4 bg-gray-300">

          <h1 className="text-3xl font-bold mb-6 text-blue-800">Monitoreo de Corriente</h1>
          <PhaseButtons />
          <div className="w-full max-w-4xl flex-1">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
